---
#  Installs Docker on the target Ubuntu system
- name: Docker | Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker | Add docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
    state: present

- name: Docker | Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Docker | Install Docker Module for Python
  ansible.builtin.pip:
    name: docker

- name: Docker | Install Docker-Compose plugin
  ansible.builtin.pip:
    name: docker-compose

- name: Docker | Add user {{ USER }} to docker group
  ansible.builtin.user:
    name: "{{ USER }}"
    groups: docker
    append: "yes"

- name: Docker | Start docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
