---
- name: Ansible copy directory to the remote server
  copy:
    src: ./files/
    dest: /wireguard

- name: Start Docker containers using Docker-Compose
  community.docker.docker_compose:
    project_src: /wireguard
    state: present
  register: output

# - name: Start Docker containers using Docker-Compose
#   command: docker-compose -f /wireguard/docker-compose.yml up -d
#   register: output

- name: Watch docker-compose output
  debug:
    var: output

- name: Pause before finishing
  pause:
    seconds: 15
# - name: Copy individual files
#   synchronize:
#     src: "{{ item }}"
#     dest: ../wg_client_configs/oci
#     mode: pull
#   with_items:
#     - "/wireguard/config/peer1"
#     - "/wireguard/config/peer2"
#     - "/wireguard/config/peer3"
#     - "/wireguard/config/peer4"
#     - "/wireguard/config/peer5"
#     - "/wireguard/config/peer6"
#     - "/wireguard/config/peer7"
#     - "/wireguard/config/peer8"
#     - "/wireguard/config/peer9"
#     - "/wireguard/config/peer10"
