---
- name: Wireguard | Copy directory to remote server
  ansible.builtin.copy:
    src: ./files/
    dest: /wireguard

- name: Wireguard | Start Docker containers using Docker-Compose
  community.docker.docker_compose:
    project_src: /wireguard
    state: present
  register: output

- name: Wireguard | Watch docker-compose output
  ansible.builtin.debug:
    var: output

- name: Wireguard | Check Wireguard admin panel availability
  ansible.builtin.wait_for:
    port: "{{ wireguard_ui_port }}"
    delay: 10
