---
- name: Wireguard | Copy directory to remote server
  ansible.builtin.copy:
    src: ./files/
    dest: /wireguard

- name: Wireguard | Start Docker containers using Docker-Compose
  community.docker.docker_compose:
    project_src: /wireguard
    state: present
  register: output

- name: Wireguard | Watch docker-compose output
  ansible.builtin.debug:
    var: output

- name: Pause before finishing
  pause:
    seconds: 15
# - name: Copy individual files
#   synchronize:
#     src: "{{ item }}"
#     dest: ../wg_client_configs/oci
#     mode: pull
#   with_items:
#     - "/wireguard/config/peer1"
#     - "/wireguard/config/peer2"
#     - "/wireguard/config/peer3"
#     - "/wireguard/config/peer4"
#     - "/wireguard/config/peer5"
#     - "/wireguard/config/peer6"
#     - "/wireguard/config/peer7"
#     - "/wireguard/config/peer8"
#     - "/wireguard/config/peer9"
#     - "/wireguard/config/peer10"
