---
- name: Run "apt-get update"
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all apt packages
  ansible.builtin.apt:
    upgrade: dist

- name: Install apt prerequisites
  ansible.builtin.package:
    name:
      - curl
      - git
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - haveged
    state: latest
