---
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install prerequisites
  package:
    name:
      - curl
      - git
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - haveged
    state: present

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes