---
- name: Run "apt-get update"
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install apt prerequisites
  ansible.builtin.package:
    name:
      - curl
      - git
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - haveged
    state: latest

- name: Install pip prerequisites
  pip:
    name:
      - openssl>22.1.0
      -
    state: latest
# - name: Upgrade all apt packages
#   apt:
#     upgrade: dist
#     force_apt_get: yes
