---
- name: Create local Wireguard Client config directory
  hosts: local

  tasks:
    - import_tasks: tasks/local.yml

- name: Install Docker Docker-Compose and dependencies.
  hosts: aws
  become: true
  vars:
    DOCKER_COMPOSE_VERSION: "1.27.1"
    USER: "root"

  pre_tasks:
    - import_tasks: tasks/pretasks.yml

  tasks:
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/dockercompose.yml
    - import_tasks: tasks/aws_wirehole.yml

  post_tasks:
    - import_tasks: tasks/posttasks.yml